

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RolandSall/artist-block-configuration
          search-paths:
            - 'dev'
            - 'staging'
            - 'production'
  application:
    name: configuration_service

eureka:
  client:
    serviceUrl:
      defaultZone: "https://artist-block-discovery-service.herokuapp.com/eureka"
  instance:
    prefer-ip-address: true


server:
  port: 8888

management:
  endpoint:
    web:
      exposure:
        include: '*'

