eureka:
  client:
    serviceUrl:
      defaultZone: "https://artist-block-discovery-service.herokuapp.com/eureka"
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: health
server:
  port: 8090
spring:
  application:
    name: gateway_service