# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
      - 'artist-block-backend-netcore-services/**'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: artist-block-backend-netcore-services/account-service/  

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Check Current Directory
      - name: Check Directory
        run: ls

      - 
        name: Run Test
        run: cd .. & dotnet test

      -  
        name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN  }}   

      -
        name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/artist-block-account-service

      - 
        name: Run Bat file
        run: ./account-service-heroku-deployement-workflow.bat
          
      - 
        name: login to heroku container
        run: docker login --username=_ --password=${{ secrets.HEROKU_API_KEY }} registry.heroku.com
        
      -
        name: Tag Image for heroku deployement
        run: docker tag rolandsall24/artist-block-account-service:1.0.5 registry.heroku.com/artist-block-account-service/web

      -  
        name: Check for current images
        run: docker images
     
      -
        name: Push Registry
        run: docker push registry.heroku.com/artist-block-account-service/web
      
      -
        name: Log In As User
        uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          justlogin: true
      
      -
        name: Release Version
        run: heroku container:release web -a artist-block-account-service
            